"""
Topology configuration for the OEC RQ-VAE downlink study.

Single source of truth shared by:
  - generate_sim_inputs.py  (builds the UDP burst schedule + ns-3 config)
  - extract_topology.py     (summarises the generated Hypatia state)

Design principle: ALL SATELLITES ARE EQUAL.
Every satellite can (a) capture an image, (b) run the RQ-VAE encoder on-board
(the "compute" / RQ node role), and (c) relay traffic over its inter-satellite
links. There is no special class of compute satellites. Which satellites are
"doing computation" at a given instant is simply whichever ones are currently
overhead an imaged region and downlinking to a ground station.

Ground stations: we use the EXISTING Hypatia top-100 city list that the
satellite state was already generated with (no regeneration needed). We select
5 of those 100 stations, spread around the globe by longitude so visibility
geometry and ISL routing differ between them.
"""

# ---------------------------------------------------------------------------
# Constellation (Starlink 550km shell, as generated by Hypatia)
# ---------------------------------------------------------------------------
CONSTELLATION = {
    "name": "Starlink-550",
    "altitude_km": 550,
    "inclination_deg": 53.0,
    "num_orbital_planes": 72,
    "sats_per_plane": 22,
    "num_satellites": 72 * 22,          # 1584
    "isl_pattern": "+Grid",             # 4 ISLs/sat: 2 intra-plane, 2 inter-plane
    "isls_per_satellite": 4,
    "total_isls": 72 * 22 * 4 // 2,     # 3168
    # Measured from our generated state:
    "max_gsl_length_m": 1_089_686,
    "max_isl_length_m": 5_016_591,
}

# In Hypatia, node IDs are: satellites 0 .. (num_satellites - 1),
# then ground stations num_satellites .. num_satellites + 99, in file order.
FIRST_GS_NODE_ID = CONSTELLATION["num_satellites"]   # 1584

# ---------------------------------------------------------------------------
# Ground stations (AC nodes) — selected from the EXISTING top-100 list
# ---------------------------------------------------------------------------
# Path (relative to hypatia_sim/) to the Hypatia top-100 ground station file
# the satellite state was generated with.
TOP100_PATH = (
    "../hypatia/paper/satellite_networks_state/input_data/"
    "ground_stations_cities_sorted_by_estimated_2025_pop_top_100.basic.txt"
)

# How many of the existing 100 stations to use as AC nodes.
NUM_GROUND_STATIONS = 5

# Selection mode:
#   "spread"  -> pick NUM_GROUND_STATIONS stations evenly spaced by longitude
#   list[int] -> explicit station indices (0..99) into the top-100 file
GROUND_STATION_SELECTION = "spread"

# Fallback used only if TOP100_PATH cannot be read (e.g. testing off-server).
# These are the first five entries of the top-100 list (confirmed to exist),
# so their node IDs (1584..1588) match the generated state.
FALLBACK_STATIONS = [
    (0, "Tokyo",      35.6895,  139.69171),
    (1, "Delhi",      28.66667,  77.21667),
    (2, "Shanghai",   31.22222, 121.45806),
    (3, "Sao-Paulo", -23.5475,  -46.63611),
    (4, "Mumbai",     19.073975, 72.880838),
]

# ---------------------------------------------------------------------------
# Imaging / compute satellites (RQ nodes) — one assigned per ground station
# ---------------------------------------------------------------------------
# All satellites are interchangeable, so these are representative source nodes
# spread across different orbital planes (sat_id = plane*22 + index). The TRUE
# satellite overhead each station at t=0 is reported by extract_topology.py;
# plug those in for a pure single-GSL-hop downlink, or leave the spread to force
# realistic ISL relaying.
SOURCE_SATELLITES = [0, 330, 660, 990, 1320]   # planes 0, 15, 30, 45, 60

# ---------------------------------------------------------------------------
# Link parameters
# ---------------------------------------------------------------------------
GSL_DATA_RATE_MBPS = 100.0      # ground-to-satellite downlink (Starlink Gen2-ish)
ISL_DATA_RATE_MBPS = 10000.0    # laser inter-satellite link (10 Gbps)
QUEUE_SIZE_PKTS    = 1000

# ---------------------------------------------------------------------------
# Simulation timing
# ---------------------------------------------------------------------------
DYNAMIC_STATE_UPDATE_NS = 100_000_000      # 100 ms (matches generated state)
STATE_DURATION_S        = 200              # length of generated satellite state


def gs_node_id(index):
    """Return the Hypatia node ID for the station at top-100 index `index`."""
    return FIRST_GS_NODE_ID + index


def sat_plane_index(sat_id):
    """Return (orbital_plane, index_in_plane) for a satellite node ID."""
    spp = CONSTELLATION["sats_per_plane"]
    return sat_id // spp, sat_id % spp
